name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    env:
      VSIX_FILE: "anki-editor-${{ github.ref_name }}.vsix"
    steps:
      - name: Download vsix release asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "tags/${{ github.ref_name }}"
          file: ${{ env.VSIX_FILE }}
      - name: (test) List directory content
        run: ls -l
      - name : (test) Show node & npm version & python version
        run: node --version && npm --version && python --version
