name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    env:
      VSIX_FILE: "anki-editor-${{ github.ref_name }}.vsix"
    steps:
      - name: Download vsix release asset
        uses: robinraju/release-downloader@v1
        with:
          tag: ${{ github.ref_name }}
          fileName: ${{ env.VSIX_FILE }}
          tarBall: false
          zipBall: false
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ env.VSIX_FILE }}
          dryRun: true
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          registryUrl: https://open-vsx.org
          extensionFile: ${{ env.VSIX_FILE }}
          dryRun: true
